### ISSUE TITLE
Требуются доработки!

### ISSUE THREAD

**Issue by nzhukov** [ctel-prj-mng/2-wireframe-130218-stuklovao#1]
Проверено! 

В целом - **хорошо**, требуются **доработки**! Но надо обратить внимание на размер элементов в мобильной версии. Особенно, при проектировании под экран 320*480. Элементы должны быть больше! Осознайте какого физического размера будет ваш логотип при таком размере экрана.

**Comment by stuklovao** [comment]
Добавлен новый макет
